services:
  dbt-database:
    image: postgres:17.2
    container_name: vitari
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - ./database:/var/lib/postgresql/data
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql

#1C4GZEFGTREJF77N76ZMY4FU
